<?php

namespace MeSomb\Model;

use DateTime;

/**
 * Class Wallet
 * @package MeSomb\Model
 *
 * @property int $id - The wallet's id generated by MeSomb
 * @property string $number - The wallet's number
 * @property string $country - The wallet's country
 * @property string $status - The wallet's status
 * @property DateTime $last_activity - The wallet's last activity
 * @property numeric $balance - The wallet's balance
 * @property string $first_name - The wallet owner's first name
 * @property string $last_name - The wallet owner's last name
 * @property string email - The wallet owner's email
 * @property string $phone_number - The wallet owner's phone number
 * @property string $gender - The wallet owner's gender
 */
class Wallet
{
    /**
     * @var array
     */
    private $data;

    /**
     * @var int The wallet's id generated by MeSomb
     */
    public $id;

    /**
     * @var string
     */
    public $number;

    /**
     * @var string
     */
    public $country;

    /**
     * @var string
     */
    public $status;

    /**
     * @var DateTime
     */
    public $last_activity;

    /**
     * @var double
     */
    public $balance;

    /**
     * @var string
     */
    public $first_name;

    /**
     * @var string
     */
    public $last_name;

    /**
     * @var string
     */
    public $email;

    /**
     * @var string
     */
    public $phone_number;

    /**
     * @var string
     */
    public $gender;

    /**
     *
     */
    public function __construct($data)
    {
        $this->data = $data;

        $this->id = $data['id'];
        $this->number = $data['number'];
        $this->country = $data['country'];
        $this->status = $data['status'];
        $this->last_activity = $data['last_activity'] != null ? new DateTime($data['last_activity']) : null;
        $this->balance = $data['balance'];
        $this->first_name = $data['first_name'];
        $this->last_name = $data['last_name'];
        $this->email = $data['email'];
        $this->phone_number = $data['phone_number'];
        $this->gender = $data['gender'];
    }

    /**
     * @return array
     */
    public function getData() {
        return $this->data;
    }
}